name: Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: news-tracker
  NODE_VERSION: "20.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          SCRAPER_API_URL: ${{ secrets.SCRAPER_API_URL }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          NEXT_PUBLIC_NEWS_API: ${{ secrets.NEXT_PUBLIC_NEWS_API }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Configure Azure Web App
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          app-settings-json: |
            [
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "0"
              },
              {
                "name": "WEBSITE_NODE_DEFAULT_VERSION",
                "value": "20.x"
              },
              {
                "name": "STARTUP_COMMAND",
                "value": "node server.js"
              }
            ]
          mask-inputs: false
